config/routes.rb
Rails.application.routes.draw do
  resources :chat_rooms, only: [:new, :create, :show, :index]
  root 'chat_rooms#index'

  devise_for :users
  #root to: 'pages#index'
  get '/secret', to: 'pages#secret', as: :secret
  
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  
  after_create_commit { MessageBroadcastJob.perform_later(self) }
  validates :body, presence: true, length: {maximum: 1000}
  
  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
  
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
    def configure_permitted_parameters
      #devise_parameter_sanitizer.for(:sign_up) << :name
      #devise_parameter_sanitizer.for(:account_update) << :name
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  
  def index
    @chat_rooms = ChatRoom.all
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = "New chat room created"
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def new
    @chat_room = ChatRoom.new
  end
  
  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  end
  
  private
  
    def chat_room_params
      params.require(:chat_room).permit(:title)
    end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
  
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/create.html.erb
<h1>ChatRooms#create</h1>
<p>Find me in app/views/chat_rooms/create.html.erb</p>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add new Chat Room</h1>
<%= form_for(@chat_room) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>
  
  <%= f.submit "Add!", class: 'btn btn-primary' %>
    
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Secret', secret_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviceDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
    
    <%= yield :top_content %>
    
    <div class="container">
        <h1><%= yield :header %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>

app/views/pages/secret.html.erb
<% header "Secret!" %>